document.writeln("<div class=\"yqlj\">");
document.writeln("    <h2><span>友情链接<\/span><\/h2>");
document.writeln("    <ul>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("      <li><a href=\"#\" target=\"_blank\">中国教育网<\/a><\/li>");
document.writeln("    <\/ul>");
document.writeln("  <\/div>");
document.writeln("<div class=\"footer\" style=\" border-top:#CCCCCC solid 4px; clear:both;\">");
document.writeln("<div style=\"width:500px; margin:0px 0 15px 230px; padding:0px; overflow:hidden; text-align:center; clear:both;\">");
document.writeln("<p>关于我们|版权声明|加入我们|意见反馈|帮助中心|网站地图|客户服务|站长统计<\/p>");
document.writeln("<p>客服邮箱：kefu@263.net  客服电话：400-680-8875<\/p>");
document.writeln("<p>技术支持：北京四联基业信息科技有限公司<\/p>");
document.writeln("<\/div>");
document.writeln("<\/div>")